global:
  scrape_interval: 10s # 拉取间隔
  evaluation_interval: 10s # 评估间隔



scrape_configs:
  - job_name: 'telegraf'
    scrape_interval: 5s # 覆盖拉取间隔
    static_configs:
      - targets: ['telegraf:9090'] # 拉取的目标
